name: kernel module CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: configure
        run: sudo apt install build-essential flex bison make
      - name: install kernel headers
        run: sudo apt install linux-headers-$(uname-r) linux-modules-$(uname -r)
      - name: KERN_DIR=/lib/modules/$(uname -r)/build make
        run: make